import html2canvas from "html2canvas";
import jsPDF from "jspdf";

function chainToText(chain) {
  const lines = [];
  lines.push("=== VocalChainAI — Signal Chain ===\n");

  if (chain.eq) {
    lines.push(`[1] EQ — ${chain.eq.label}`);
    for (const b of chain.eq.bands) {
      const freq = b.freq >= 1000 ? `${(b.freq / 1000).toFixed(1)}kHz` : `${b.freq}Hz`;
      const gain = b.type === "HPF" ? "cut" : `${b.gain > 0 ? "+" : ""}${b.gain}dB`;
      lines.push(`    ${b.type} ${freq} ${gain} Q:${b.q}${b.note ? ` — ${b.note}` : ""}`);
    }
    lines.push("");
  }

  const sections = [
    ["Compressor", chain.comp],
    ["De-Esser", chain.deesser],
    ["Pitch Correction", chain.pitch],
    ["Saturation", chain.saturation],
    ["Vocal Doubling", chain.doubling],
    ["Delay", chain.delay],
    ["Reverb", chain.reverb],
  ];

  let step = 2;
  for (const [title, data] of sections) {
    if (!data) continue;
    lines.push(`[${step}] ${title} — ${data.label || ""}`);
    if (data.plugin) lines.push(`    Plugin: ${data.plugin}`);
    if (data.plugins) lines.push(`    Plugins: ${data.plugins.join(", ")}`);
    const skip = new Set(["label", "note", "plugin", "plugins", "eqTip", "bands"]);
    for (const [k, v] of Object.entries(data)) {
      if (skip.has(k)) continue;
      lines.push(`    ${k}: ${Array.isArray(v) ? v.join(", ") : v}`);
    }
    if (data.note) lines.push(`    Note: ${data.note}`);
    lines.push("");
    step++;
  }

  lines.push("Generated by VocalChainAI");
  return lines.join("\n");
}

function chainToJSON(chain) {
  return JSON.stringify(chain, null, 2);
}

export default function ExportPanel({ chain }) {
  if (!chain) return null;

  const handleCopyText = () => {
    const text = chainToText(chain);
    navigator.clipboard.writeText(text);
  };

  const handleCopyMarkdown = () => {
    const lines = [];
    lines.push("# VocalChainAI — Signal Chain\n");

    if (chain.eq) {
      lines.push(`## 1. EQ — ${chain.eq.label}`);
      lines.push("| Type | Freq | Gain | Q | Note |");
      lines.push("|------|------|------|---|------|");
      for (const b of chain.eq.bands) {
        const freq = b.freq >= 1000 ? `${(b.freq / 1000).toFixed(1)}kHz` : `${b.freq}Hz`;
        const gain = b.type === "HPF" ? "-" : `${b.gain > 0 ? "+" : ""}${b.gain}dB`;
        lines.push(`| ${b.type} | ${freq} | ${gain} | ${b.q} | ${b.note || ""} |`);
      }
      lines.push("");
    }

    const sections = [
      ["Compressor", chain.comp],
      ["De-Esser", chain.deesser],
      ["Pitch Correction", chain.pitch],
      ["Saturation", chain.saturation],
      ["Vocal Doubling", chain.doubling],
      ["Delay", chain.delay],
      ["Reverb", chain.reverb],
    ];

    let step = 2;
    for (const [title, data] of sections) {
      if (!data) continue;
      lines.push(`## ${step}. ${title} — ${data.label || ""}`);
      if (data.plugin) lines.push(`**Plugin:** ${data.plugin}`);
      if (data.plugins) lines.push(`**Plugins:** ${data.plugins.join(", ")}`);
      const skip = new Set(["label", "note", "plugin", "plugins", "eqTip", "bands"]);
      for (const [k, v] of Object.entries(data)) {
        if (skip.has(k)) continue;
        lines.push(`- **${k}:** ${Array.isArray(v) ? v.join(", ") : v}`);
      }
      if (data.note) lines.push(`\n> ${data.note}`);
      lines.push("");
      step++;
    }

    lines.push("---\n*Generated by VocalChainAI*");
    navigator.clipboard.writeText(lines.join("\n"));
  };

  const handleDownloadJSON = () => {
    const json = chainToJSON(chain);
    const blob = new Blob([json], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "vocalchain.json";
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleExportImage = async () => {
    const el = document.querySelector(".chain-result");
    if (!el) return;
    const canvas = await html2canvas(el, {
      backgroundColor: getComputedStyle(document.documentElement).getPropertyValue("--bg").trim(),
      scale: 2,
    });
    const url = canvas.toDataURL("image/png");
    const a = document.createElement("a");
    a.href = url;
    a.download = "vocalchain.png";
    a.click();
  };

  const handleExportPDF = async () => {
    const el = document.querySelector(".chain-result");
    if (!el) return;
    const canvas = await html2canvas(el, {
      backgroundColor: getComputedStyle(document.documentElement).getPropertyValue("--bg").trim(),
      scale: 2,
    });
    const imgData = canvas.toDataURL("image/png");
    const pdf = new jsPDF("p", "mm", "a4");
    const pdfW = pdf.internal.pageSize.getWidth();
    const pdfH = (canvas.height * pdfW) / canvas.width;
    pdf.addImage(imgData, "PNG", 0, 0, pdfW, pdfH);
    pdf.save("vocalchain.pdf");
  };

  return (
    <div className="export-panel">
      <h3>Export</h3>
      <div className="export-buttons">
        <button className="export-btn" onClick={handleCopyText}>Copy Text</button>
        <button className="export-btn" onClick={handleCopyMarkdown}>Copy Markdown</button>
        <button className="export-btn" onClick={handleDownloadJSON}>Download JSON</button>
        <button className="export-btn" onClick={handleExportImage}>Save as PNG</button>
        <button className="export-btn" onClick={handleExportPDF}>Save as PDF</button>
      </div>
    </div>
  );
}
