/**
 * Cubase StudioEQ .vstpreset 생성 (실험적)
 *
 * VST3 Preset 형식:
 * - Header: "VST3" magic + version + ClassID (32 bytes)
 * - Chunk List: "List" + size + "Comp" chunk + "Info" chunk
 * - Comp chunk: 플러그인 상태 바이너리 (파라미터 값들)
 * - Info chunk: XML 메타데이터
 *
 * StudioEQ ClassID: 미리 알려진 값 사용
 * 이 구현은 Cubase 내장 StudioEQ 4밴드를 대상으로 합니다.
 *
 * 주의: 이 기능은 실험적이며, Cubase 버전에 따라 동작하지 않을 수 있습니다.
 */

// StudioEQ의 파라미터 레이아웃 (Cubase 12/13 기준 추정)
// 각 밴드: bypass(int32), type(int32), freq(float64), gain(float64), q(float64)
// Global: bypass(int32), output_gain(float64)

const STUDIO_EQ_CLASS_ID = "C4B83426B44C4B3C8BCC7D7513946323"; // Steinberg StudioEQ

function float64ToBytes(val) {
  const buf = new ArrayBuffer(8);
  new Float64Array(buf)[0] = val;
  return new Uint8Array(buf);
}

function int32ToBytes(val) {
  const buf = new ArrayBuffer(4);
  new Int32Array(buf)[0] = val;
  return new Uint8Array(buf);
}

function stringToBytes(str) {
  return new TextEncoder().encode(str);
}

function hexToBytes(hex) {
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < hex.length; i += 2) {
    bytes[i / 2] = parseInt(hex.substring(i, i + 2), 16);
  }
  return bytes;
}

// EQ band type mapping to StudioEQ type index
const BAND_TYPE_MAP = {
  HPF: 1,      // High Pass
  LPF: 2,      // Low Pass
  LShelf: 3,   // Low Shelf
  HShelf: 4,   // High Shelf
  Bell: 5,     // Parametric
};

function buildCompChunk(bands) {
  // StudioEQ has 4 bands
  // We map our 5-band preset to 4 bands (skip or merge as needed)
  const eqBands = bands.slice(0, 4);

  const parts = [];

  // Global bypass: off
  parts.push(int32ToBytes(0));

  for (let i = 0; i < 4; i++) {
    const band = eqBands[i];
    if (band) {
      parts.push(int32ToBytes(0)); // bypass: off
      parts.push(int32ToBytes(BAND_TYPE_MAP[band.type] || 5)); // type
      parts.push(float64ToBytes(band.freq)); // frequency
      parts.push(float64ToBytes(band.type === "HPF" ? 0 : band.gain)); // gain
      parts.push(float64ToBytes(band.q || 1.0)); // Q
    } else {
      // Empty band (bypassed)
      parts.push(int32ToBytes(1)); // bypass: on
      parts.push(int32ToBytes(5)); // type: parametric
      parts.push(float64ToBytes(1000)); // freq
      parts.push(float64ToBytes(0)); // gain
      parts.push(float64ToBytes(1.0)); // Q
    }
  }

  // Output gain
  parts.push(float64ToBytes(0.0));

  // Concatenate all parts
  const totalSize = parts.reduce((sum, p) => sum + p.length, 0);
  const result = new Uint8Array(totalSize);
  let offset = 0;
  for (const part of parts) {
    result.set(part, offset);
    offset += part.length;
  }
  return result;
}

function buildInfoChunk(presetName) {
  const xml = `<?xml version="1.0" encoding="utf-8"?>
<MetaInfo>
  <Attribute id="MediaType" value="VstPreset" type="string"/>
  <Attribute id="PlugInName" value="StudioEQ" type="string"/>
  <Attribute id="PlugInCategory" value="Fx|EQ" type="string"/>
  <Attribute id="PlugInVendor" value="Steinberg Media Technologies" type="string"/>
  <Attribute id="Name" value="${presetName}" type="string"/>
  <Attribute id="Comment" value="Generated by VocalChainAI" type="string"/>
</MetaInfo>`;
  return stringToBytes(xml);
}

function writeChunkHeader(id, data) {
  // Chunk: 4-byte ID + 8-byte size (little-endian) + data
  const header = new Uint8Array(12);
  const idBytes = stringToBytes(id.padEnd(4, " ").substring(0, 4));
  header.set(idBytes, 0);
  const sizeView = new DataView(header.buffer);
  // Use two 32-bit writes for 64-bit size (little-endian)
  sizeView.setUint32(4, data.length, true);
  sizeView.setUint32(8, 0, true); // high 32 bits

  const result = new Uint8Array(12 + data.length);
  result.set(header, 0);
  result.set(data, 12);
  return result;
}

/**
 * Generate a .vstpreset file blob for Cubase StudioEQ
 * @param {Object} eq - EQ preset object with bands array
 * @param {string} name - Preset name
 * @returns {Blob} - Binary .vstpreset file
 */
export function generateVstPreset(eq, name = "VocalChainAI Preset") {
  if (!eq || !eq.bands) return null;

  const compData = buildCompChunk(eq.bands);
  const infoData = buildInfoChunk(name);

  const compChunk = writeChunkHeader("Comp", compData);
  const infoChunk = writeChunkHeader("Info", infoData);

  // List chunk wraps Comp and Info
  const listContent = new Uint8Array(compChunk.length + infoChunk.length);
  listContent.set(compChunk, 0);
  listContent.set(infoChunk, compChunk.length);
  const listChunk = writeChunkHeader("List", listContent);

  // VST3 Header: magic "VST3" + version(4 bytes) + classID(32 bytes hex → 16 bytes)
  const magic = stringToBytes("VST3");
  const version = int32ToBytes(1);
  const classId = hexToBytes(STUDIO_EQ_CLASS_ID);

  const headerSize = magic.length + version.length + classId.length;
  const totalSize = headerSize + listChunk.length;
  const result = new Uint8Array(totalSize);

  let offset = 0;
  result.set(magic, offset); offset += magic.length;
  result.set(version, offset); offset += version.length;
  result.set(classId, offset); offset += classId.length;
  result.set(listChunk, offset);

  return new Blob([result], { type: "application/octet-stream" });
}

/**
 * Download a .vstpreset file
 */
export function downloadVstPreset(eq, name) {
  const blob = generateVstPreset(eq, name);
  if (!blob) return;

  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${name.replace(/[^a-zA-Z0-9_-]/g, "_")}.vstpreset`;
  a.click();
  URL.revokeObjectURL(url);
}
